services:
  postgresql:
    container_name: postgresql
    env_file:
    - .env
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    # volumes:
    #     - db-data:/var/lib/postgresql/15/main
    networks:
    - transcendence_network
    restart: on-failure

  django:
    container_name: django
    env_file:
    - .env
    build:
      context: ./django
      dockerfile: Dockerfile
    depends_on:
    - postgresql
    networks:
    - transcendence_network
    restart: on-failure
    ports:
    - 8000:8000

# volumes:
#     db-data:
#         driver: local
#         driver_opts:
#             type: none
#             device: ~/sgoinfre/data-pong/postgresql
#             o: bind

networks:
  transcendence_network:
    driver: bridge
