services:
  postgresql:
    container_name: postgresql
    env_file:
    - .env
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    networks:
    - transcendence_network
    restart: on-failure
    ports:
    - 5432:5432

  django:
    container_name: django
    env_file:
    - .env
    build:
      context: ./django
      dockerfile: Dockerfile
    depends_on:
    - postgresql
    networks:
    - transcendence_network
    restart: on-failure

  nginx:
    container_name: nginx
    env_file:
    - .env
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
    - django
    networks:
    - transcendence_network
    restart: on-failure
    ports:
    - 4444:4444

networks:
  transcendence_network:
    driver: bridge
