services:
    postgresql:
        container_name: postgresql
        env_file:
            - .env
        build:
            context: ./postgresql
            dockerfile: Dockerfile
        volumes:
            - db-data:/var/lib/postgresql/15/main
        networks:
            - db
        restart: on-failure
        expose:
            - 3306

volumes:
    db-data:
        driver: local
        driver_opts:
            type: none
            device: ~/sgoinfre/data-pong/postgresql
            o: bind

networks:
    db: {
        driver: bridge
    }
