# Generated by Django 4.2.4 on 2024-06-08 15:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=4)),
                ('created_at', models.DateTimeField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('winner', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('game_id', models.IntegerField()),
                ('scored', models.IntegerField()),
                ('killed', models.IntegerField()),
                ('bounces', models.IntegerField()),
                ('won', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('mail', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('a2f', models.BooleanField()),
            ],
        ),
    ]
